services:
  postgres:
    image: postgres:18
    container_name: labclin_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: labclin_db
      POSTGRES_USER: labclin_user
      POSTGRES_PASSWORD: labclin_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
